<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrderMicroservice.Database\OrderMicroservice.Database.csproj" />
    <ProjectReference Include="..\OrderMicroservice.Domain\OrderMicroservice.Domain.csproj" />
    <ProjectReference Include="..\OrderMicroservice.Common\OrderMicroservice.Common.csproj" />
  </ItemGroup>

</Project>
