/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#faf8ff",
        error: "#ba1a1a",
        error_container: "#ffdad6",
        inverse_on_surface: "#f0f0fb",
        inverse_primary: "#b8c4ff",
        inverse_surface: "#2e3039",
        on_background: "#191b23",
        on_error: "#ffffff",
        on_error_container: "#93000a",
        on_primary: "#ffffff",
        on_primary_container: "#efefff",
        on_primary_fixed: "#001453",
        on_primary_fixed_variant: "#173bab",
        on_secondary: "#ffffff",
        on_secondary_container: "#394c84",
        on_secondary_fixed: "#00174b",
        on_secondary_fixed_variant: "#31447b",
        on_surface: "#191b23",
        on_surface_variant: "#434655",
        on_tertiary: "#ffffff",
        on_tertiary_container: "#ffede6",
        on_tertiary_fixed: "#360f00",
        on_tertiary_fixed_variant: "#7d2d00",
        outline: "#737686",
        outline_variant: "#c3c6d7",
        primary: "#2b4bb9",
        primary_container: "#4865d3",
        primary_fixed: "#dde1ff",
        primary_fixed_dim: "#b8c4ff",
        secondary: "#495c95",
        secondary_container: "#acbfff",
        secondary_fixed: "#dbe1ff",
        secondary_fixed_dim: "#b4c5ff",
        surface: "#faf8ff",
        surface_bright: "#faf8ff",
        surface_container: "#ededf9",
        surface_container_high: "#e7e7f3",
        surface_container_highest: "#e1e2ed",
        surface_container_low: "#f3f3fe",
        surface_container_lowest: "#ffffff",
        surface_dim: "#d9d9e5",
        surface_tint: "#3755c3",
        surface_variant: "#e1e2ed",
        tertiary: "#943700",
        tertiary_container: "#bc4800",
        tertiary_fixed: "#ffdbcd",
        tertiary_fixed_dim: "#ffb596"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Manrope', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
